// Code generated by stanc v2.32.1
#include <stan/model/model_header.hpp>
namespace just_occupancy_no_detection_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 20> locations_array__ =
  {" (found before start of program)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 16, column 2 to column 14)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 17, column 2 to column 21)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 18, column 2 to column 22)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 64, column 2 to column 18)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 66, column 0 to line 68, column 62)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 65, column 17 to line 69, column 3)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 65, column 2 to line 69, column 3)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 26, column 2 to column 26)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 27, column 2 to column 31)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 28, column 2 to column 32)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 55, column 2 to line 57, column 58)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 3, column 4 to column 19)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 5, column 8 to column 9)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 5, column 2 to column 35)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 8, column 9 to column 10)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 8, column 2 to column 21)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 9, column 9 to column 10)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 9, column 2 to column 22)",
  " (in 'C:/Users/ilebe/Documents/!Masters!/Analysis/AbundanceConditionalOccupancy/Model/just_occupancy_no_detection.stan', line 64, column 9 to column 10)"};
class just_occupancy_no_detection_model final : public model_base_crtp<just_occupancy_no_detection_model> {
 private:
  int I;
  std::vector<int> y;
  Eigen::Matrix<double,-1,1> latitude_data__;
  Eigen::Matrix<double,-1,1> longitude_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> latitude{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> longitude{nullptr, 0};
 public:
  ~just_occupancy_no_detection_model() {}
  just_occupancy_no_detection_model(stan::io::var_context& context__,
                                    unsigned int random_seed__ = 0,
                                    std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "just_occupancy_no_detection_model_namespace::just_occupancy_no_detection_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 12;
      context__.validate_dims("data initialization", "I", "int",
        std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      current_statement__ = 12;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "I", I, 0);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("y", "I", I);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(I)});
      y = std::vector<int>(I, std::numeric_limits<int>::min());
      current_statement__ = 14;
      y = context__.vals_i("y");
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 14;
      stan::math::check_less_or_equal(function__, "y", y, 1);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("latitude", "I", I);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "latitude", "double",
        std::vector<size_t>{static_cast<size_t>(I)});
      latitude_data__ = Eigen::Matrix<double,-1,1>::Constant(I,
                          std::numeric_limits<double>::quiet_NaN());
      new (&latitude)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(latitude_data__.data(), I);
      {
        std::vector<local_scalar_t__> latitude_flat__;
        current_statement__ = 16;
        latitude_flat__ = context__.vals_r("latitude");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 16;
          stan::model::assign(latitude, latitude_flat__[(pos__ - 1)],
            "assigning variable latitude", stan::model::index_uni(sym1__));
          current_statement__ = 16;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 17;
      stan::math::validate_non_negative_index("longitude", "I", I);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "longitude", "double",
        std::vector<size_t>{static_cast<size_t>(I)});
      longitude_data__ = Eigen::Matrix<double,-1,1>::Constant(I,
                           std::numeric_limits<double>::quiet_NaN());
      new (&longitude)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(longitude_data__.data(), I);
      {
        std::vector<local_scalar_t__> longitude_flat__;
        current_statement__ = 18;
        longitude_flat__ = context__.vals_r("longitude");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 18;
          stan::model::assign(longitude, longitude_flat__[(pos__ - 1)],
            "assigning variable longitude", stan::model::index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("y_rep", "I", I);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "just_occupancy_no_detection_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.1",
             "stancflags = "};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "just_occupancy_no_detection_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ beta_0 = DUMMY_VAR__;
      current_statement__ = 1;
      beta_0 = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_latitude = DUMMY_VAR__;
      current_statement__ = 2;
      beta_latitude = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_longitude = DUMMY_VAR__;
      current_statement__ = 3;
      beta_longitude = in__.template read<local_scalar_t__>();
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_0, 0, 0.5));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_latitude, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_longitude, 0, 1));
        current_statement__ = 11;
        lp_accum__.add(stan::math::bernoulli_logit_lpmf<propto__>(y,
                         stan::math::add(
                           stan::math::add(beta_0,
                             stan::math::multiply(beta_latitude, latitude)),
                           stan::math::multiply(beta_longitude, longitude))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "just_occupancy_no_detection_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double beta_0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      beta_0 = in__.template read<local_scalar_t__>();
      double beta_latitude = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      beta_latitude = in__.template read<local_scalar_t__>();
      double beta_longitude = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      beta_longitude = in__.template read<local_scalar_t__>();
      out__.write(beta_0);
      out__.write(beta_latitude);
      out__.write(beta_longitude);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> y_rep =
        Eigen::Matrix<double,-1,1>::Constant(I,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      for (int i = 1; i <= I; ++i) {
        current_statement__ = 5;
        stan::model::assign(y_rep,
          stan::math::bernoulli_logit_rng(((beta_0 + (beta_latitude *
            stan::model::rvalue(latitude, "latitude",
              stan::model::index_uni(i)))) + (beta_longitude *
            stan::model::rvalue(longitude, "longitude",
              stan::model::index_uni(i)))), base_rng__),
          "assigning variable y_rep", stan::model::index_uni(I));
      }
      out__.write(y_rep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ beta_0 = DUMMY_VAR__;
      current_statement__ = 1;
      beta_0 = in__.read<local_scalar_t__>();
      out__.write(beta_0);
      local_scalar_t__ beta_latitude = DUMMY_VAR__;
      current_statement__ = 2;
      beta_latitude = in__.read<local_scalar_t__>();
      out__.write(beta_latitude);
      local_scalar_t__ beta_longitude = DUMMY_VAR__;
      current_statement__ = 3;
      beta_longitude = in__.read<local_scalar_t__>();
      out__.write(beta_longitude);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta_0", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_latitude",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta_longitude",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ beta_0 = DUMMY_VAR__;
      current_statement__ = 1;
      beta_0 = context__.vals_r("beta_0")[(1 - 1)];
      out__.write(beta_0);
      local_scalar_t__ beta_latitude = DUMMY_VAR__;
      current_statement__ = 2;
      beta_latitude = context__.vals_r("beta_latitude")[(1 - 1)];
      out__.write(beta_latitude);
      local_scalar_t__ beta_longitude = DUMMY_VAR__;
      current_statement__ = 3;
      beta_longitude = context__.vals_r("beta_longitude")[(1 - 1)];
      out__.write(beta_longitude);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta_0", "beta_latitude",
                "beta_longitude"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"y_rep"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(I)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "beta_0");
    param_names__.emplace_back(std::string() + "beta_latitude");
    param_names__.emplace_back(std::string() + "beta_longitude");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_rep" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "beta_0");
    param_names__.emplace_back(std::string() + "beta_latitude");
    param_names__.emplace_back(std::string() + "beta_longitude");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_rep" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_latitude\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_longitude\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_latitude\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_longitude\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (I);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (I);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = just_occupancy_no_detection_model_namespace::just_occupancy_no_detection_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return just_occupancy_no_detection_model_namespace::profiles__;
}
#endif